### ISSUE TITLE
兼容Egg2.0

### ISSUE THREAD

**Issue by 634750802** [hubcarl/egg-webpack-vue#1]
```
app.view.resolve = function* (name) {
      return name;
    };
```
导致await app.viewManager.resolve()结果为空对象，导致服务端渲染崩掉。

https://github.com/hubcarl/egg-vue-webpack-boilerplate/issues/47

没有阅读其他源码不确定其他部分是否有相关问题。 本地把node_modules中的这句话改为
```
app.view.resolve = function (name) {
      return name;
    };
```
能够正常渲染。

**Comment by hubcarl** [comment]
https://github.com/hubcarl/egg-webpack-vue/pull/2
